services:
  # === === Import Service === ===
  ar2-import-api:
    container_name: ar2-import-api
    image: ${REPONAME}/ar2-import-api:${TAG}
    build: 
      context: ./
      dockerfile: Dockerfile
    environment:
      - APP_PORT=${APP_PORT}
      - HASURA_HOST=${HASURA_HOST}
      - HASURA_PORT=${HASURA_PORT}
      - GQL_ENDPOINT=${GQL_ENDPOINT}
      - HASURA_GRAPHQL_ADMIN_SECRET=${HASURA_GRAPHQL_ADMIN_SECRET}
      - SERVICE_VERSION=${SERVICE_VERSION}
      - DEVELOPMENT=${DEVELOPMENT}
      - MINIO_HOST=${MINIO_HOST}
      - MINIO_PORT=${MINIO_PORT}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME}
      - KAFKA_HOST=${KAFKA_HOST}
      - KAFKA_PORT=${KAFKA_PORT}
      - KAFKA_IMPORT_TOPIC=${KAFKA_IMPORT_TOPIC}
      - KAFKA_SERVICE_TOPIC=${KAFKA_SERVICE_TOPIC}
    ports:
      - ${APP_PORT}:${APP_PORT}
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
    networks:
      - ar-network
  # === === Minio Service === ===
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./storage/minio:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --address ":9000" --console-address ":9001" /data
# === Network ===
networks:
  ar-network:
    driver: bridge
    name: ar-network