version: "3.7"

services:
  # === === App Services === ===
  ar2-import:
    image: elzdar/ar2-import:latest
    build:
      dockerfile: ./docker/ar2-import.Dockerfile
      context: .
    environment:
      - APP_PORT=${APP_PORT}
      - LOG_LEVEL=${LOG_LEVEL}
      - HASURA_ADDRESS=${HASURA_ADDRESS}
      - GQL_ENDPOINT=${GQL_ENDPOINT}
      - HASURA_GRAPHQL_ADMIN_SECRET=${HASURA_GRAPHQL_ADMIN_SECRET}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME}
      - NATS_URL=${NATS_URL}
      - NATS_SUBJECT=${NATS_SUBJECT}
      - TEMPORAL_ENDPOINT=${TEMPORAL_ENDPOINT}
      - TEMPORAL_NAMESPACE=${TEMPORAL_NAMESPACE}
    ports:
      - ${APP_PORT}:${APP_PORT}
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - ar-network
      
# === Network ===
networks:
  ar-network:
    driver: bridge
    name: ar-network
