version: "3.7"

services:
  # === === Temporal Worker === ===
  ar2-import-worker:
    container_name: ar2-import-worker
    image: ${REPONAME}/ar2-import-worker:${TAG}
    build:
      dockerfile: ./docker/ar2-import-worker.Dockerfile
      context: .
    environment:
      - LOG_LEVEL=${LOG_LEVEL}
      - HASURA_HOST=${HASURA_HOST}
      - HASURA_PORT=${HASURA_PORT}
      - GQL_ENDPOINT=${GQL_ENDPOINT}
      - HASURA_GRAPHQL_ADMIN_SECRET=${HASURA_GRAPHQL_ADMIN_SECRET}
      - MINIO_HOST=${MINIO_HOST}
      - MINIO_PORT=${MINIO_PORT}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME}
      - MINIO_HOST_PUBLIC=${MINIO_HOST_PUBLIC}
      - TEMPORAL_HOST=${TEMPORAL_HOST}
      - TEMPORAL_PORT=${TEMPORAL_PORT}
      - TEMPORAL_NAMESPACE=${TEMPORAL_NAMESPACE}
    deploy:
      restart_policy:
        condition: on-failure

  # === === App Services === ===
  ar2-import-api:
    container_name: ar2-import-api
    image: ${REPONAME}/ar2-import-api:${TAG}
    build:
      dockerfile: ./docker/ar2-import.Dockerfile
      context: .
    environment:
      - APP_PORT=${APP_PORT}
      - LOG_LEVEL=${LOG_LEVEL}
      - HASURA_HOST=${HASURA_HOST}
      - HASURA_PORT=${HASURA_PORT}
      - GQL_ENDPOINT=${GQL_ENDPOINT}
      - HASURA_GRAPHQL_ADMIN_SECRET=${HASURA_GRAPHQL_ADMIN_SECRET}
      - MINIO_HOST=${MINIO_HOST}
      - MINIO_PORT=${MINIO_PORT}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME}
      - MINIO_HOST_PUBLIC=${MINIO_HOST_PUBLIC}
      - NATS_URL=${NATS_URL}
      - NATS_SUBJECT=${NATS_SUBJECT}
      - TEMPORAL_HOST=${TEMPORAL_HOST}
      - TEMPORAL_PORT=${TEMPORAL_PORT}
      - TEMPORAL_NAMESPACE=${TEMPORAL_NAMESPACE}
    ports:
      - ${APP_PORT}:${APP_PORT}
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - ar2-import-worker