name: ar2-import - Main CI

env:
  image_prefix: ghcr.io/mssfoobar/ar2-import
  manifest_repo: mssfoobar/ar2-infra
  manifest_branch: main
  src_branch: main
  org_name: mssfoobar
  app_name: ar2-import

on:
  workflow_dispatch:

jobs:
  test:
    name: "Execute tests"
    runs-on: ubuntu-latest
    steps:
      - run: env
