name: ar2-import - Main CI

env:
  image_prefix: ghcr.io/mssfoobar/ar2-import
  manifest_repo: mssfoobar/ar2-infra
  manifest_branch: main
  src_branch: main
  org_name: mssfoobar
  app_name: ar2-import

on:
  workflow_dispatch:

concurrency:
  group: ci-ar2-import-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test1:
    name: "Execute test 1"
    runs-on: ubuntu-latest
    steps:
      - run: env

  test2:
    name: "Execute test 2"
    runs-on: ubuntu-latest
    needs:
      - test1
    strategy:
      matrix:
        include:
          - image: ${{ env.image_prefix }}_1
          - image: ${{ env.image_prefix }}_2
          - image: ${{ env.image_prefix }}_3

    steps:
      - name: "matrix ${{ matrix.image }}"
        run: echo ${{ matrix.image }}